apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: utxo-tracker
data:
  HTTP_PORT: "8080"
  HTTP_IDLE_TIMEOUT: "30"
  HTTP_SHUTDOWN_GRACE_PERIODVEL: "30"
  MONITORING_HTTP_PORT: "8081"
  TRACING_EXPORTER_ENDPOINT: "http://jaeger-collector.observe.svc.cluster.local:4318/v1/traces"
  ACCOUNT_SERVICE_DSN: "postgresql://as:as@asdb.utxo-tracker.svc.cluster.local:5432/as?sslmode=disable"
