apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: utxo-tracker
spec:
  selector:
    app: account-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 81
    targetPort: 8081
    name: metrics
